const fail = (): never => {
    throw new Error('Плановая ошибка')
}
